#ifndef ARROWS_H
#define ARROWS_H

#include <stdbool.h>
#include <stdint.h>

#include "lvgl.h"

/* 8-bit alpha masks generated by tools/gen_arrows.py; tint with img_recolor.
 * Returns NULL for direction codes that have no arrow. */
const lv_img_dsc_t *arrow_for_direction(uint8_t direction, bool small);

#endif
